#!/bin/bash

# Output the content-type header required for HTTP response
echo "Content-Type: text/html"
echo ""

# HTML content with a basic example of a floral-themed webpage
cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample CGI Script</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #e0f7fa;
            color: #00695c;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            text-align: center;
            padding: 20px;
            border: 2px solid #004d40;
            border-radius: 10px;
            background-color: #ffffff;
        }
        h1 {
            color: #004d40;
        }
        .flower {
            width: 100px;
            height: 100px;
            background-color: #ff8a80;
            border-radius: 50%;
            margin: 10px auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to My CGI Script</h1>
        <p>This page is dynamically generated by a Bash CGI script!</p>
        <div class="flower"></div>
        <p>Enjoy this simple floral design as a demonstration.</p>
    </div>
</body>
</html>
EOF
